version: '3.9'

services:
  munchpos: 
    image: munchpos/server
    restart: always
    networks: 
      munchposnetwork:
    deploy:
      replicas: ${MUNCHPOS_CORE_INSTANCES}
      placement:
        max_replicas_per_node: 1
    depends_on:
      - munchpos-db
    environment:
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
      JWT_SECRET: ${JWT_SECRET}
      HASH_SALT: ${HASH_SALT}
  munchpos-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    networks: 
      munchposnetwork:
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_NAME: ${DB_NAME:-munchpos}
      POSTGRES_USER: ${DB_USERNAME:-munchpos}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-munchpos}
    ports:
      - 5432:5432
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  munchposnetwork:
    name: munchposnetwork
